services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./data/uploads:/app/data/uploads

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./data/uploads:/data/uploads
